package org.fiftieshousewife.cleancode.core;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

public final class HtmlReportWriter {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z").withZone(ZoneOffset.UTC);

    private static final String STYLES_RESOURCE = "/html-report/styles.css";
    private static final String STYLES = loadResource(STYLES_RESOURCE);

    private HtmlReportWriter() {}

    public static void write(final AggregatedReport report, final Path outputFile) throws IOException {
        write(report, outputFile, "");
    }

    public static void write(final AggregatedReport report, final Path outputFile,
                             final String repositoryUrl) throws IOException {
        final Path parent = outputFile.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(outputFile, render(report, repositoryUrl));
    }

    private static String render(final AggregatedReport report, final String repositoryUrl) {
        final StringBuilder html = new StringBuilder();
        appendDocumentStart(html, report);
        appendSeveritySummary(html, report);

        if (report.findings().isEmpty()) {
            html.append("    <p class=\"clean\">No violations found. The code is clean.</p>\n");
        } else {
            HtmlFindingsSection.appendByCode(html, report.findings(), repositoryUrl);
            HtmlFindingsSection.appendToolSummary(html, report.findings());
        }

        appendFooter(html, report);
        html.append("</body>\n</html>\n");
        return html.toString();
    }

    private static void appendDocumentStart(final StringBuilder html, final AggregatedReport report) {
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("  <meta charset=\"UTF-8\">\n");
        html.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("  <title>Clean Code Report — ").append(HtmlEscaping.escape(report.projectName()));
        html.append("</title>\n");
        html.append("  <style>\n").append(STYLES).append("  </style>\n");
        html.append("</head>\n<body>\n");
        html.append("  <header>\n");
        html.append("    <h1>Clean Code Analysis</h1>\n");
        html.append("    <p>").append(HtmlEscaping.escape(report.projectName()));
        if (report.projectVersion() != null) {
            html.append(" v").append(HtmlEscaping.escape(report.projectVersion()));
        }
        html.append("</p>\n");
        html.append("  </header>\n");
        html.append("  <main>\n");
    }

    private static void appendSeveritySummary(final StringBuilder html, final AggregatedReport report) {
        final Map<Severity, List<Finding>> bySeverity = report.bySeverity();
        final int errors = bySeverity.getOrDefault(Severity.ERROR, List.of()).size();
        final int warnings = bySeverity.getOrDefault(Severity.WARNING, List.of()).size();
        final int info = bySeverity.getOrDefault(Severity.INFO, List.of()).size();

        html.append("    <div class=\"summary\">\n");
        html.append("      <span class=\"badge error\">").append(errors).append(" errors</span>\n");
        html.append("      <span class=\"badge warning\">").append(warnings);
        html.append(" warnings</span>\n");
        html.append("      <span class=\"badge info\">").append(info).append(" info</span>\n");
        html.append("    </div>\n");
    }

    private static void appendFooter(final StringBuilder html, final AggregatedReport report) {
        final String timestamp = TIMESTAMP_FORMAT.format(report.generatedAt());
        html.append("  </main>\n");
        html.append("  <footer>\n");
        html.append("    <p>Generated by Clean Code Plugin &mdash; ").append(HtmlEscaping.escape(timestamp));
        html.append("</p>\n");
        html.append("    <p>").append(report.findings().size()).append(" total findings</p>\n");
        html.append("  </footer>\n");
    }

    private static String loadResource(final String path) {
        try (InputStream in = HtmlReportWriter.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IllegalStateException("Missing resource: " + path);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (final IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
