package org.fiftieshousewife.cleancode.core;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import static org.fiftieshousewife.cleancode.core.HtmlEscaping.escape;
import static org.fiftieshousewife.cleancode.core.HtmlFindingsRenderer.appendFindingsByCode;
import static org.fiftieshousewife.cleancode.core.HtmlFindingsRenderer.appendToolSummary;

public final class HtmlReportWriter {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z").withZone(ZoneOffset.UTC);

    private HtmlReportWriter() {}

    public static void write(final AggregatedReport report, final Path outputFile) throws IOException {
        write(report, outputFile, "");
    }

    public static void write(final AggregatedReport report, final Path outputFile,
                              final String repositoryUrl) throws IOException {
        final Path parent = outputFile.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(outputFile, render(report, repositoryUrl));
    }

    private static String render(final AggregatedReport report, final String repositoryUrl) {
        final StringBuilder html = new StringBuilder();
        appendDocumentStart(html, report);
        appendSeveritySummary(html, report);

        if (report.findings().isEmpty()) {
            html.append("    <p class=\"clean\">No violations found. The code is clean.</p>\n");
        } else {
            appendFindingsByCode(html, report.findings(), repositoryUrl);
            appendToolSummary(html, report.findings());
        }

        appendFooter(html, report);
        appendDocumentEnd(html);
        return html.toString();
    }

    private static void appendDocumentStart(final StringBuilder html, final AggregatedReport report) {
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("  <meta charset=\"UTF-8\">\n");
        html.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("  <title>Clean Code Report — ").append(escape(report.projectName()));
        html.append("</title>\n");
        appendStyles(html);
        html.append("</head>\n<body>\n");
        appendHeader(html, report);
        html.append("  <main>\n");
    }

    private static void appendHeader(final StringBuilder html, final AggregatedReport report) {
        html.append("  <header>\n");
        html.append("    <h1>Clean Code Analysis</h1>\n");
        html.append("    <p>").append(escape(report.projectName()));
        if (report.projectVersion() != null) {
            html.append(" v").append(escape(report.projectVersion()));
        }
        html.append("</p>\n");
        html.append("  </header>\n");
    }

    private static void appendStyles(final StringBuilder html) {
        html.append("  <style>\n").append(HtmlReportStyles.css()).append("  </style>\n");
    }

    private static void appendSeveritySummary(final StringBuilder html, final AggregatedReport report) {
        final Map<Severity, List<Finding>> bySeverity = report.bySeverity();
        html.append("    <div class=\"summary\">\n");
        appendSeverityBadge(html, "error", countOf(bySeverity, Severity.ERROR), "errors");
        appendSeverityBadge(html, "warning", countOf(bySeverity, Severity.WARNING), "warnings");
        appendSeverityBadge(html, "info", countOf(bySeverity, Severity.INFO), "info");
        html.append("    </div>\n");
    }

    private static int countOf(final Map<Severity, List<Finding>> bySeverity, final Severity severity) {
        return bySeverity.getOrDefault(severity, List.of()).size();
    }

    private static void appendSeverityBadge(final StringBuilder html, final String cssClass,
                                             final int count, final String label) {
        html.append("      <span class=\"badge ").append(cssClass).append("\">");
        html.append(count).append(' ').append(label).append("</span>\n");
    }

    private static void appendFooter(final StringBuilder html, final AggregatedReport report) {
        final String timestamp = TIMESTAMP_FORMAT.format(report.generatedAt());
        html.append("  </main>\n");
        html.append("  <footer>\n");
        html.append("    <p>Generated by Clean Code Plugin &mdash; ").append(escape(timestamp));
        html.append("</p>\n");
        html.append("    <p>").append(report.findings().size()).append(" total findings</p>\n");
        html.append("  </footer>\n");
    }

    private static void appendDocumentEnd(final StringBuilder html) {
        html.append("</body>\n</html>\n");
    }
}
