package io.github.fiftieshousewife.cleancode.plugin;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.fiftieshousewife.cleancode.annotations.HeuristicCode;
import org.gradle.api.DefaultTask;
import org.gradle.api.Project;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.TreeMap;

@DisableCachingByDefault(because = "aggregates every submodule's latest findings.json via convention paths resolved at runtime")
public abstract class SummaryReportTask extends DefaultTask {

    private record Counts(int errors, int warnings, int info) {
        Counts plus(final Counts other) {
            return new Counts(errors + other.errors, warnings + other.warnings, info + other.info);
        }

        int total() {
            return errors + warnings + info;
        }
    }

    @TaskAction
    public void run() throws IOException {
        final Project rootProject = getProject().getRootProject();
        final Path rootDir = rootProject.getProjectDir().toPath();
        final Path reportsDir = rootDir.resolve("docs/reports");
        Files.createDirectories(reportsDir);

        final Map<String, Counts> byModule = new LinkedHashMap<>();
        final Map<String, Integer> byCode = new TreeMap<>();
        accumulate(byModule, byCode, "(root)", rootDir,
                rootProject.getLayout().getBuildDirectory().get().getAsFile().toPath());
        for (final Project sub : rootProject.getSubprojects()) {
            accumulate(byModule, byCode, sub.getName(), rootDir,
                    sub.getLayout().getBuildDirectory().get().getAsFile().toPath());
        }

        Counts totals = new Counts(0, 0, 0);
        for (final Counts c : byModule.values()) {
            totals = totals.plus(c);
        }

        final Path htmlSummary = reportsDir.resolve("index.html");
        final Path mdSummary = reportsDir.resolve("SUMMARY.md");
        Files.writeString(htmlSummary, renderHtml(byModule, totals));
        Files.writeString(mdSummary, renderMarkdown(byModule, byCode, totals));
        getLogger().lifecycle("Wrote summary reports: {}, {}", htmlSummary, mdSummary);
    }

    private void accumulate(final Map<String, Counts> byModule,
                            final Map<String, Integer> byCode,
                            final String name,
                            final Path rootDir,
                            final Path buildDir) {
        final Path findings = buildDir.resolve("reports/clean-code/findings.json");
        if (!Files.exists(findings)) {
            byModule.put(name, new Counts(0, 0, 0));
            return;
        }
        try (Reader reader = Files.newBufferedReader(findings)) {
            final JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
            final JsonArray array = root.getAsJsonArray("findings");
            if (array == null) {
                byModule.put(name, new Counts(0, 0, 0));
                return;
            }
            int errors = 0;
            int warnings = 0;
            int info = 0;
            for (final JsonElement element : array) {
                final JsonObject finding = element.getAsJsonObject();
                final String code = finding.get("code").getAsString();
                if (isEnvironmentDependent(code)) {
                    continue;
                }
                final String severity = finding.get("severity").getAsString();
                switch (severity) {
                    case "ERROR" -> errors++;
                    case "WARNING" -> warnings++;
                    case "INFO" -> info++;
                    default -> { }
                }
                byCode.merge(code, 1, Integer::sum);
            }
            byModule.put(name, new Counts(errors, warnings, info));
        } catch (IOException e) {
            byModule.put(name, new Counts(0, 0, 0));
        }
    }

    private static boolean isEnvironmentDependent(final String code) {
        try {
            return HeuristicCode.valueOf(code).isEnvironmentDependent();
        } catch (IllegalArgumentException unknownCode) {
            return false;
        }
    }

    private String renderMarkdown(final Map<String, Counts> byModule,
                                  final Map<String, Integer> byCode,
                                  final Counts totals) {
        final StringBuilder sb = new StringBuilder();
        sb.append("# Clean Code — self-analysis summary\n\n");
        sb.append("Auto-generated by `./scripts/dogfood.sh` (`./gradlew cleanCodeSummary`).\n");
        sb.append("Deterministic: contains no absolute paths, timestamps, or machine-specific\n");
        sb.append("content, so local and CI runs produce byte-identical output. CI fails if\n");
        sb.append("this file drifts from the committed state.\n\n");
        sb.append("Code reference: [HEURISTICS.md](../clean-code/HEURISTICS.md) ");
        sb.append("(extracted from the plugin jar by `./gradlew cleanCodeWriteHeuristics`).\n\n");

        sb.append("**Total: ").append(totals.total())
                .append(" findings** (").append(totals.errors()).append(" errors · ")
                .append(totals.warnings()).append(" warnings · ")
                .append(totals.info()).append(" info)\n\n");

        sb.append("## By module\n\n");
        sb.append("| Module | Errors | Warnings | Info | Total |\n");
        sb.append("|---|---:|---:|---:|---:|\n");
        byModule.forEach((name, counts) -> sb.append("| ").append(name)
                .append(" | ").append(counts.errors())
                .append(" | ").append(counts.warnings())
                .append(" | ").append(counts.info())
                .append(" | ").append(counts.total())
                .append(" |\n"));
        sb.append("| **Total** | **").append(totals.errors())
                .append("** | **").append(totals.warnings())
                .append("** | **").append(totals.info())
                .append("** | **").append(totals.total())
                .append("** |\n\n");

        sb.append("## By heuristic code\n\n");
        sb.append("| Code | Count |\n");
        sb.append("|---|---:|\n");
        byCode.entrySet().stream()
                .sorted(Map.Entry.<String, Integer>comparingByValue().reversed()
                        .thenComparing(Map.Entry.comparingByKey()))
                .forEach(entry -> sb.append("| ").append(entry.getKey())
                        .append(" | ").append(entry.getValue())
                        .append(" |\n"));
        return sb.toString();
    }

    private String renderHtml(final Map<String, Counts> byModule, final Counts totals) {
        final StringBuilder sb = new StringBuilder();
        sb.append("<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"UTF-8\">")
                .append("<title>Clean Code summary</title><style>")
                .append("body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
                        + "margin:0;padding:2rem;color:#222;background:#fafafa;}")
                .append("h1{margin:0 0 0.25rem;font-size:1.5rem;}")
                .append("p.meta{color:#666;margin:0 0 1.5rem;font-size:0.9rem;}")
                .append("table{border-collapse:collapse;min-width:680px;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);}")
                .append("th,td{padding:0.6rem 1rem;border-bottom:1px solid #eee;text-align:left;}")
                .append("th{background:#1a1a2e;color:#fff;font-weight:600;}")
                .append("td.num{text-align:right;font-variant-numeric:tabular-nums;}")
                .append("tr.total td{font-weight:700;background:#f0f0f5;border-top:2px solid #1a1a2e;}")
                .append(".err{color:#c0392b;}")
                .append(".warn{color:#e67e22;}")
                .append(".info{color:#7f8c8d;}")
                .append("a{color:#1a73e8;text-decoration:none;}")
                .append("a:hover{text-decoration:underline;}")
                .append("</style></head><body>");

        sb.append("<h1>Clean Code — self-analysis summary</h1>");
        sb.append("<p class=\"meta\">Aggregates every module's <code>findings.json</code> ")
                .append("and sums across the project. Regenerated by ")
                .append("<code>./scripts/dogfood.sh</code>; CI fails if this file ")
                .append("drifts from the committed state.</p>");

        sb.append("<table><thead><tr><th>Module</th>")
                .append("<th class=\"num err\">Errors</th>")
                .append("<th class=\"num warn\">Warnings</th>")
                .append("<th class=\"num info\">Info</th>")
                .append("<th class=\"num\">Total</th></tr></thead><tbody>");
        byModule.forEach((name, counts) -> sb.append("<tr>")
                .append("<td>")
                .append("<a href=\"").append(reportLink(name)).append("\">").append(escape(name)).append("</a>")
                .append("</td>")
                .append("<td class=\"num err\">").append(counts.errors()).append("</td>")
                .append("<td class=\"num warn\">").append(counts.warnings()).append("</td>")
                .append("<td class=\"num info\">").append(counts.info()).append("</td>")
                .append("<td class=\"num\">").append(counts.total()).append("</td>")
                .append("</tr>"));
        sb.append("<tr class=\"total\"><td>Total</td>")
                .append("<td class=\"num err\">").append(totals.errors()).append("</td>")
                .append("<td class=\"num warn\">").append(totals.warnings()).append("</td>")
                .append("<td class=\"num info\">").append(totals.info()).append("</td>")
                .append("<td class=\"num\">").append(totals.total()).append("</td>")
                .append("</tr>");
        sb.append("</tbody></table>");

        sb.append("<p class=\"meta\" style=\"margin-top:1.5rem\">")
                .append("E1 findings (outdated dependencies) are emitted only at the Gradle root — ")
                .append("sub-modules skip them once the catalog is anchored at <code>gradle/libs.versions.toml</code>. ")
                .append("Counts are post-<code>@SuppressCleanCode</code>; raw pre-suppression baseline ")
                .append("(1,313) lives in <code>experiment/baseline/*.json</code>.")
                .append("</p>");
        sb.append("</body></html>\n");
        return sb.toString();
    }

    private String reportLink(final String name) {
        return "(root)".equals(name) ? "root.html" : name + ".html";
    }

    private String escape(final String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
